---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todd-one
  labels:
    app: todd-one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todd-one
  template:
    metadata:
      labels:
        app: todd-one
    spec:
      containers:
        - name: todd-one
          image: docker.io/parsontodd/todd-one:latest
          ports:
            - containerPort: 8080